export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  LIVE_MAP: '/live-map',
  ALERTS: '/alerts',
  SOS: '/sos',
  SHELTERS: '/shelters',
  VOLUNTEERS: '/volunteers',
  RESOURCES: '/resources',
  PROFILE: '/profile',
  NOT_FOUND: '*',
  ADMIN_DASHBOARD: '/admin',
  MANAGE_ALERTS: '/admin/alerts',
  MANAGE_SHELTERS: '/admin/shelters',
  MANAGE_RESOURCES: '/admin/resources',
  MANAGE_VOLUNTEERS: '/admin/volunteers',
  SOS_REQUESTS: '/admin/sos-requests',
}
